name: Publish

on:
  workflow_dispatch:

env:
  DAGGER_VERSION: "0.21.8"

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Publish images
    runs-on: depot-ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dagger
        uses: dagger/dagger-for-github@v8.4.1
        with:
          version: ${{ env.DAGGER_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Login to ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build and push postgres image
        run: |
          make build-push
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
